### ISSUE TITLE
Macaroon LND gRPC Env only allows path (not hex macaroon)

### ISSUE THREAD

**Issue by frennkie** [arcbtc/lnbits#20]
Macaroon LND gRPC Env only allows path (not hex macaroon)

Content of .env:

```
...
LND_ADMIN_MACAROON=0201...4f4c
...
```

Error

```
nactiveRpcError of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "Getting metadata from plugin failed with error: [Errno 36] File name too long: '0201...4f4c'" debug_error_string = "{"created":"@15878418
```

**Comment by arcbtc** [comment]
When running on rest we used strings, I'll get the rest LND funding source prepared for the blitz then check with the string,
Maybe it's an rpc thing

**Comment by arcbtc** [comment]
Added the LND rest funding source, which works with hex strings for the macaroons
