### ISSUE TITLE
Unable to send from wallet

### ISSUE THREAD

**Issue by joe-rodgers** [arcbtc/lnbits#5]
![send](https://user-images.githubusercontent.com/25499388/71040845-3b277100-20ed-11ea-944b-03e992975490.PNG)
 Unable to send from wallet. I created an invoice for the complete balance, 1000 sats, and the wallet will not send. 

Once I paste in the send invoice, and hit send, nothing happens. 

Windows, Chrome Browser 
Zap Desktop LN Invoice

+++++++++++++++++++

I tried a 100 sat send and it worked. I think there must be something in the code that prevents a user from deleting the entire wallet.

Then balance was 900, so I tried a 900 sat send, and it would not send.
I tried an 899 sat send and it wouldn't go through either, thinking I needed to keep 1 sat balance.

Finally I tried an 800 sat send and it worked, balance in wallet is 100 sat.

**Comment by joe-rodgers** [comment]
I tried a 100 sat send and it worked. I think there must be something in the code that prevents a user from deleting the entire wallet.

**Comment by arcbtc** [comment]
You need to leave a few sats in the wallet to cover any potential fees, try 999

**Comment by arcbtc** [comment]
@fiatjaf put in a workaround, so you should be able to send all the money now!
