### ISSUE TITLE
Missing Send Transaction

### ISSUE THREAD

**Issue by HamishMacEwan** [arcbtc/lnbits#7]
![image](https://user-images.githubusercontent.com/388061/71770543-9634e100-2f92-11ea-828a-8451454bd046.png)

Balance from displayed transactions: 10,448.4 sats
The graph is displaying this amount.

Difference is 1337.4 which is an amount I sent from lnbits to lntxbot (plus fees of 0.4?):

```
⚡️ RECEIVED  on 4 Jan 2020 at 9:40AM 
From the lnbits

Hash: bea1ed0affbdc73075bdb77affeb570d57a266bac8149ab509d273cdfaf2ead9
Amount: 1337 sat (0.10 USD)
```

**Comment by fiatjaf** [comment]
Is it still wrong after a refresh?

**Comment by arcbtc** [comment]
Closing I think
