### ISSUE TITLE
LNURLw Extension Fails

### ISSUE THREAD

**Issue by HamishMacEwan** [arcbtc/lnbits#9]
I installed the LNURLw extension and created an LNURL Withdraw link:

https://lnbits.com/displaywithdraw?id=864c2d05045d44b4b462a13a7b484241

I tested the link with BLW and successfully pulled 25 sats from the lnbits wallet (the second one in my set).  The "No. uses" was decremented and the balance of the wallet reduced.

Later attempts with BLW, Zeus & lntxbot all failed with perhaps lntxbot being the most helpful:

Error: Got status 400 on callback https://lnbits.com/v1/lnurlwithdraw/be178/

While I doubt it will fix the problem, units for the wait time would be helpful, and whether the wait time applies to all requests or only those from the same... node, wallet, or whatever.

Also the Wallet link goes to the primary wallet, though the LNURLw is against the secondary.

PS.  I have succeeded again, after a 7 hour pause, with BLW, but now, again, no wallet works.

**Comment by arcbtc** [comment]
I just pulled x2 withdraws out one on WoS and one with BLW. Now it says "withdraw spent" :(
I have had a similar bug report from others, so will investigate further today

**Comment by arcbtc** [comment]
Couldn't replicate issue
